expedientes = [
    {"expediente": "021636", "entidad": "REGIONAL HUANUCO"},
    {"expediente": "020776", "entidad": "MUNICIPAL DISTRITAL HUANUCO - HUAMALIES - JIRCAN"},
    {"expediente": "020207", "entidad": "MUNICIPAL DISTRITAL HUANUCO - AMBO - CONCHAMARCA"},
    {"expediente": "020005", "entidad": "MUNICIPAL DISTRITAL HUANUCO - PACHITEA - MOLINO"},
    {"expediente": "019962", "entidad": "MUNICIPAL DISTRITAL HUANUCO - PACHITEA - CHAGLLA"},
    {"expediente": "019611", "entidad": "MUNICIPAL DISTRITAL HUANUCO - HUAMALIES - CHAVIN DE PARIARCA"},
    {"expediente": "019578", "entidad": "MUNICIPAL DISTRITAL HUANUCO - PACHITEA - UMARI"},
    {"expediente": "019552", "entidad": "MUNICIPAL DISTRITAL HUANUCO - AMBO - SAN FRANCISCO"},
    {"expediente": "019523", "entidad": "MUNICIPAL PROVINCIAL HUANUCO - HUAMALIES"},
    {"expediente": "019515", "entidad": "MUNICIPAL DISTRITAL HUANUCO - HUAMALIES - JACAS GRANDE"},
    {"expediente": "019480", "entidad": "MUNICIPAL DISTRITAL HUANUCO - HUAMALIES - MIRAFLORES"},
    {"expediente": "018543", "entidad": "MUNICIPAL DISTRITAL HUANUCO - HUAMALIES - PUÑOS"},
    {"expediente": "018415", "entidad": "MUNICIPAL DISTRITAL HUANUCO - HUAMALIES - PUNCHAO"},
    {"expediente": "018361", "entidad": "MUNICIPAL DISTRITAL HUANUCO - HUANUCO - SAN PABLO DE PILLAO"},
    {"expediente": "018196", "entidad": "MUNICIPAL DISTRITAL HUANUCO - AMBO - COLPAS"},
    {"expediente": "018089", "entidad": "MUNICIPAL DISTRITAL HUANUCO - HUANUCO - AMARILIS"},
    {"expediente": "018028", "entidad": "MUNICIPAL DISTRITAL HUANUCO - HUANUCO - QUISQUI"},
    {"expediente": "017792", "entidad": "MUNICIPAL DISTRITAL HUANUCO - HUAMALIES - ARANCAY"},
    {"expediente": "017727", "entidad": "MUNICIPAL DISTRITAL HUANUCO - HUANUCO - SAN FRANCISCO DE CAYRAN"},
    {"expediente": "017668", "entidad": "MUNICIPAL DISTRITAL HUANUCO - HUANUCO - SANTA MARIA DEL VALLE"},
    {"expediente": "016931", "entidad": "MUNICIPAL DISTRITAL HUANUCO - HUANUCO - PILLCO MARCA"},
    {"expediente": "016815", "entidad": "MUNICIPAL DISTRITAL HUANUCO - HUANUCO - YACUS"},
    {"expediente": "016774", "entidad": "MUNICIPAL DISTRITAL HUANUCO - HUACAYBAMBA - COCHABAMBA"},
    {"expediente": "016749", "entidad": "MUNICIPAL DISTRITAL HUANUCO - DOS DE MAYO - YANAS"},
    {"expediente": "016717", "entidad": "MUNICIPAL DISTRITAL HUANUCO - DOS DE MAYO - QUIVILLA"},
    {"expediente": "016678", "entidad": "MUNICIPAL DISTRITAL HUANUCO - AMBO - CAYNA"},
    {"expediente": "016576", "entidad": "MUNICIPAL DISTRITAL HUANUCO - HUANUCO - MARGOS"},
    {"expediente": "016439", "entidad": "MUNICIPAL PROVINCIAL HUANUCO - AMBO"},
    {"expediente": "016359", "entidad": "MUNICIPAL PROVINCIAL HUANUCO - PACHITEA"},
    {"expediente": "016260", "entidad": "MUNICIPAL PROVINCIAL HUANUCO - HUANUCO"},
    {"expediente": "015878", "entidad": "MUNICIPAL DISTRITAL HUANUCO - HUANUCO - CHURUBAMBA"},
    {"expediente": "015521", "entidad": "MUNICIPAL DISTRITAL HUANUCO - HUAMALIES - TANTAMAYO"},
    {"expediente": "014985", "entidad": "MUNICIPAL DISTRITAL HUANUCO - HUANUCO - CHINCHAO"},
    {"expediente": "014890", "entidad": "MUNICIPAL DISTRITAL HUANUCO - DOS DE MAYO - SILLAPATA"},
    {"expediente": "014864", "entidad": "MUNICIPAL DISTRITAL HUANUCO - AMBO - SAN RAFAEL"},
    {"expediente": "014818", "entidad": "MUNICIPAL DISTRITAL HUANUCO - AMBO - HUACAR"},
    {"expediente": "014706", "entidad": "MUNICIPAL DISTRITAL HUANUCO - DOS DE MAYO - SHUNQUI"},
    {"expediente": "014702", "entidad": "MUNICIPAL DISTRITAL HUANUCO - DOS DE MAYO - CHUQUIS"},
    {"expediente": "014132", "entidad": "MUNICIPAL DISTRITAL HUANUCO - HUAMALIES - MONZON"},
    {"expediente": "013986", "entidad": "MUNICIPAL DISTRITAL HUANUCO - HUANUCO - SAN PEDRO DE CHAULAN"},
    {"expediente": "009782", "entidad": "#N/D"},
]